Areas/ProductManage/Models/ProductModel.cs
namespace MVC1.Models
{
    public class ProductModel
    {
        public int ProductId { get; set; }
        public string Name {get;set;}
        
        public decimal Price { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MVC1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/PlanetModel.cs
using System.Net.Mime;

namespace MVC1.Models
{
    public class PlanetModel
    {
        public int Id {get;set;}
        public string? Name { get; set; }
        public string? VnName {get;set;}
        public string? Content {get;set;}
    }
}

Areas/ProductManage/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVC1.Services;

namespace MVC1.Controllers
{

    [Area("ProductManage")]
    public class ProductController : Controller
    {
        // GET: Product
        //[Route("[Controller]")]

        private readonly ProductService _productService;
        private readonly ILogger<ProductController> _logger;

        public ProductController( ILogger<ProductController> logger, ProductService productService)
        {
            _productService = productService;
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View(_productService);
        }

    }
}

Controllers/FirstController.cs
using Microsoft.AspNetCore.Mvc;
using MVC1.Services;

namespace MVC1.Controllers
{
    public class FirstController : Controller
    {
        private readonly ILogger<FirstController> _logger;
        private readonly ProductService _productService;
        public FirstController(ILogger<FirstController> logger, ProductService productService)
        {
            _logger = logger;  
            _productService = productService;
        }
    
        public string Index()
        {
            //this.HttpContext;
            //this.Request;
            //this.Response;
            //this.RouteData;

            //this.User
            //this.ModelState
            //this.ViewData
            //this.Url
            //this.TempData
            _logger.LogWarning("warning");
            _logger.LogInformation("First Controller Index Action");
            return "Hello, First Controller!";
        }

        public object Anything() => new int []{1,2,3};


        public IActionResult Readme()
        {
            var content = @"Xin chao,
                            asp.net.mvc
                            Magnus
                            ";

                            return Content(content, "text/plain");
        }

        public IActionResult Privacy()
        {
            var url = Url.Action("Privacy", "Home");
            return LocalRedirect(url);
        }

        public IActionResult Google()
        {
            var url = "https://google.com";
            return Redirect(url);
        }   

        //ViewResult | View() 
        public IActionResult HelloView(string userName) 
        {
            if(string.IsNullOrEmpty(userName))
                userName = "Guest";
            
            //View() -> Razor Engine, read .cshtml (template)
            return View("/MyView/View1.cshtml", userName);
        }
        
        public IActionResult HelloView2(string userName) 
        {
            if(string.IsNullOrEmpty(userName))
                userName = "Guest";
            
            //View2.cshtml -> /View/First/View2.cshtml
            return View("View2", userName);
        }

        public IActionResult HelloView3(string userName) 
        {
            if(string.IsNullOrEmpty(userName))
                userName = "Guest";
            
            //View2.cshtml -> /View/First/View2.cshtml
            return View((object)userName);
        }
        public IActionResult HiView3(string userName) 
        {
            
            return View("View3");
        }

        public IActionResult ViewProduct(int? id)
        {
            var product = _productService.Where( p => p.ProductId == id ).FirstOrDefault();
            if(product == null)
            {
                TempData["StatusMessage"] = "San pham ban yeu cau ko co";
              return Redirect(Url.Action("Index", "Home"));
            }


            return View(product);
        }

        public IActionResult ViewProduct2(int? id)
        {
            var product = _productService.Where( p => p.ProductId == id ).FirstOrDefault();
            if(product == null)
                return Content($"San Pham khong ton tai");
            this.ViewData["product"] = product;
            return View();
        }
                public IActionResult ViewProduct3(int? id)
        {
            var product = _productService.Where( p => p.ProductId == id ).FirstOrDefault();
            if(product == null)
                return Content($"San Pham khong ton tai");
            this.ViewBag.product = product;
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC1.Models;

namespace MVC1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PlanetController.cs
using Microsoft.AspNetCore.Mvc;
using MVC1.Services;

namespace MVC1.Controllers
{
    [Route("he-mat-troi")]
    public class PlanetController : Controller
    {

        private readonly PlanetService _planetService;
        private readonly ILogger<PlanetController> _logger;

        public PlanetController( ILogger<PlanetController> logger, PlanetService planetService)
        {
            _planetService = planetService;
            _logger = logger;
        }
        // GET: Planet
        //        [Route("/danh-sach")] => ko ket hop => Action Route = danh-sach
        [Route("danh-sach")]
        public ActionResult Index() // => Controller Route / Action Route = he-mat-troi/danh-sach
        {
            return View();
        }

        [BindProperty(SupportsGet =true, Name = "action")]
        public string Name {get;set;}

        [Route("sao/[action]", Order = 2, Name ="route1")] // sao/Mercury
        [Route("sao/[controller]/[action]", Order = 1, Name ="route2")] // sao/
        [Route("sao/[controller]-[action]", Order = 3, Name ="route3")] // sao/
        public ActionResult Mercury()
        {
            var planet = _planetService.Where( p=>p.Name == Name).FirstOrDefault();
            return View("Details", planet);
        }


        [Route("hanhtinh/{id:int?}")] // planet/hanhtinh
        public IActionResult PlanetInfor(int? id)
        {
            if(id == null)
                return View("Index");
            var planet = _planetService.Where(p => p.Id == id).FirstOrDefault();
            return View("Details", planet);
        }
    }
}

Areas/ProductManage/Views/Product/Index.cshtml
@using MVC1.Models
@model List<ProductModel>
<h1>Product</h1>

<div class="list-group">
    @foreach (var service in @Model)
    {
        <li>
            @service.Name
        </li>
    }
</div>


<p>
    @Url.ActionLink()
</p>
<p>
    @Url.Action()
</p>

<p>
    @Url.Action("PlanetInfor", "Planet", new {id = 3})
</p>

Pages/Razor.cshtml
@page  "/aboutRazor.html"
@{
    Layout = "_Layout";
}
<h1>Gioi thieu ve Razor </h1>

<p>
    Razor là 1 template engine trong .Net, nó là template engine mặc định của ASP.Net.MVC, có chức năng render HTML từ các view (.cshtml)
    View (.cshtml) cho phép viết HTML và nhúng code c#.
</p>

Views/First/HelloView3.cshtml
@{
    Layout = "_Layout";
}
@model string

<div class="card bg-primary text-white" style="background: red; margin:30px; padding: 30px;">
    <h1> xin chao @Model</h1>
    <p>
        Ban dang tim hieu ve View 3 (.cshtml) trong ASP.Net MVC
    </p>

</div>

@this.Path

Views/First/View2.cshtml
@{
    Layout = "_Layout";
}
@model string

<div class="card bg-primary text-white" style="background: red; margin:30px; padding: 30px;">
    <h1> xin chao @Model</h1>
    <p>
        Ban dang tim hieu ve View (.cshtml) trong ASP.Net MVC
    </p>

</div>

@this.Path

Views/First/View3.cshtml
@{
    Layout = "_Layout";
}
@model string

<div class="card bg-primary text-white" style="background: rgb(46, 40, 40); margin:30px; padding: 30px;">
    <h1> xin chao @Model</h1>
    <p>
        Ban dang tim hieu ve View 3 (.cshtml) trong ASP.Net MVC
    </p>

</div>

@this.Path

Views/First/ViewProduct.cshtml
@using MVC1.Models
@{
    Layout = "_Layout";
}
@model ProductModel

<div class="card bg-primary text-white" style="background: red; margin:30px; padding: 30px;">
    <h1 class="card-header">San pham @Model.Name</h1>
    <div class="card-body">
        <p class="card-text">
          Price: @Model.Price
        </p>
    </div>


</div>

    using MVC1.Models;
#line default

Views/First/ViewProduct2.cshtml
@using MVC1.Models
@{
    var product = ViewData["product"] as ProductModel;
}

<div class="card bg-primary text-white" style="background: red; margin:30px; padding: 30px;">
    <h1 class="card-header"> @product.Name</h1>
    <div class="card-body">
        <p class="card-text">
          Price: @product.Price
        </p>
    </div>


</div>

    using MVC1.Models;
#line default

Views/First/ViewProduct3.cshtml
@using MVC1.Models
@{
    var product = ViewBag.product as ProductModel;
}

<div class="card bg-primary text-white" style="background: red; margin:30px; padding: 30px;">
    <h1 class="card-header">Bag. @product.Name</h1>
    <div class="card-body">
        <p class="card-text">
          Price: @product.Price
        </p>
    </div>


</div>

    using MVC1.Models;
#line default

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}
<partial name="_AlertMessage"/>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Planet/Details.cshtml
@model MVC1.Models.PlanetModel
<h1>@Model.Name</h1>

<div class="card w-50">
    <img src="~/planet/@(Model.Name).jpg" alt="">
    <div class="card-body">
        <div class="card-text">
            @Model.Content
        </div>
        <a class="card-link" asp-action="Index"> Cac hanh tinh</a>
    </div>
</div>

Views/Planet/Index.cshtml
@inject MVC1.Services.PlanetService planetService
<h1>Cacs hanh tinh</h1>

<div class="list-group">
    @foreach (var planet in planetService)
    {
        <a class="list-group-item list-group-item-action" asp-action="PlanetInfor" asp-route-id ="@planet.Id">
            @planet.Name
        </a>
    }

    <label>@Url.RouteUrl("route1")</label>
</div>

Views/Shared/_AlertMessage.cshtml
@{
    var data = TempData["StatusMessage"] as string;
}

@if(!string.IsNullOrEmpty(data))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @TempData["StatusMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times</span>
        </button>

    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Planet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>